NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: "output"
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "prompt" # set transfer type here # SELF_QKV+bias
  TYPE: "ssl-vit"
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "adamw"
  MOMENTUM: 0.9
  LOG_EVERY_N: 100 #100
  WARMUP_EPOCH: 10 # 10
  TOTAL_EPOCH: 100 #100
DATA:
  NAME: "test"
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "dino_vits16"
  BATCH_SIZE: 128